### ISSUE TITLE
'atom-workspace': instead of 'atom-text-editor': 

### ISSUE THREAD

**Issue by skirem** [aki77/atom-expand-region#10]
please update the readme

**Comment by aki77** [comment]
Please explain it to me more.

**Comment by ewnd9** [comment]
I believe it is about the line 22 https://github.com/aki77/atom-expand-region/blame/master/README.md#L22

Don't have a documentation link about changing but I can confirm `atom-workspace` is a working for atom v1.5.3

**Comment by aki77** [comment]
The scope is better as small as possible.
Please see the following.

https://github.com/aki77/atom-expand-region/blob/master/lib/main.coffee#L25

[4.2 Behind Atom : Keymaps In-Depth](https://atom.io/docs/latest/behind-atom-keymaps-in-depth)

**Comment by ewnd9** [comment]
Thanks for links, changed to `atom-workspace` in my config. Btw, I wonder where did I get from my original config with `atom-workspace` :confused:
