### ISSUE TITLE
Not be able to select inside HTML tag, and mis-recognise quotes

### ISSUE THREAD

**Issue by pingshunhuangalex** [aki77/atom-expand-region#18]
Hi @aki77 

Amazing package and exactly what atom is missing from the built-in packages.

However, trying it in the HTML brought up the issue below:
![image](https://cloud.githubusercontent.com/assets/17170199/19425092/810cb46c-947a-11e6-8c27-4adcc85029f6.png)
You can see that not only did it fail to select the text inside the HTML tag, it also failed to recgnise the quote appeared under the context by selecting lines of irrelavant text.

Judging from the development, I guess you're probably all tied-up and need some help (Wish I could, but I don't have the skill). Hope it will be fixed soon. Thanks.

**Comment by sgsvenkatesh** [comment]
Same issue here

![expand-region-issue](https://cloud.githubusercontent.com/assets/4642729/20551255/2c9aa1f8-b164-11e6-99c8-ad6d85cabfb7.gif)

Similar issue happens when selecting HTML attributes.

**Comment by aki77** [comment]
#4
