### ISSUE TITLE
Selection doesn't work in Atom 1.19.0

### ISSUE THREAD

**Issue by ocoka** [aki77/atom-expand-region#26]
_event.target.getModel_ here getMoodel is absent

**Comment by aki77** [comment]
It does not reproduce.
Please try Atom 1.19.1.

**Comment by ocoka** [comment]
Hi, I didn't  try to reproduce in Atom 1.19.1, but now in Atom 1.19.2 it does reproduced
![image](https://user-images.githubusercontent.com/8239290/29566321-21efbc1a-8752-11e7-8ddf-793d787327ae.png)

**Comment by ocoka** [comment]
Do you have same target as I , that: *input:hidden-input* ?
