### ISSUE TITLE
expanding "speed"

### ISSUE THREAD

**Issue by PavelA85** [aki77/atom-expand-region#3]
Hi,
Thank you for your package.
Its what I was looking for.
But there is slight problem, how can I control speed of selection?
I mean first few expanding works as expected, but after its selects method with params, its expands to whole scope.
Here is my desired expanding selection behavior 
![vs](https://cloud.githubusercontent.com/assets/2944514/10339104/5510dda6-6d12-11e5-9182-70b31cd6cd46.gif)

How can i achieve this?

**Comment by aki77** [comment]
Sorry, I can't catch what you want.
Please kindly tell me again.

**Comment by PavelAgejkin** [comment]
![atom](https://cloud.githubusercontent.com/assets/2944514/10339702/7006c99c-6d15-11e5-93a9-dcf1de197da2.gif)
compare with atom case.
Just in 3 expanding step I get all function scope selected, while expected to do this at least 7 steps

**Comment by aki77** [comment]
Please edit the `config.cson` to customize the behavior.

Example

```coffeescript
'.source.js':
  'expand-region':
    commands: [
      {
        command: 'editor:select-word'
        recursive: false
      }
      {
        command: 'editor:select-line'
        recursive: false
      }
      {
        command: 'core:select-all'
        recursive: false
      }
    ]
```

[default settings](https://github.com/aki77/atom-expand-region/blob/master/settings/expand-region.cson)

**Comment by nicooprat** [comment]
Is there any way to select HTML attribute key+value before selecting the entire line? Eg `class="foo"`.

What's more, in SCSS file the action `'expand-region:select-scope'` is selecting entire line with indentation. Any way to hack this behavior?

Thanks for your work!

**Comment by aki77** [comment]
Please see below.
https://github.com/aki77/atom-expand-region#customize-selected-regions
