### ISSUE TITLE
Select all inside HTML tags

### ISSUE THREAD

**Issue by ivancuric** [aki77/atom-expand-region#4]
Example:

``` html
<ul>
  <li class="listbox-option"><a href="">Link1</a></li>
  <li class="listbox-option"><a href="">Link2</a></li>
</ul>
```

Is it possible to configure the plugin to act in the following way?:
- when the caret is on Link1, expanding goes in the following way:
  `Link1 > a > li > both li (ul inner) > ul (including ul tags)`
- when the caret is between the `ul` and `li` tags (for example: `<ul>|<li>`, the selection is expanded to the `ul` content, that being the 2 `li` elements.

![Expand region](https://camo.githubusercontent.com/7e84f0e4d123670bc099a2ce581aef84c47590e2/687474703a2f2f61726f6e776f6f73742e6769746875622e696f2f657870616e642d746f2d68746d6c2e676966)

The reason is that i often need to add another container for some elements, and I can do this easily in ST3's [Expand Region](https://github.com/aronwoost/sublime-expand-region) in combination with emmet.

**Comment by PavelAgejkin** [comment]
Yes, that would be very nice to have!

**Comment by quaritexa** [comment]
Please add another stop for html attribute (rel="stylesheet"):
 &lt;link rel="stylesheet" type="text/css" href="assets/css/style.css"&gt;

![2015-10-26 19_00_06](https://cloud.githubusercontent.com/assets/886676/10734410/31220a94-7c14-11e5-8198-26b53cd9e8d6.gif)

**Comment by HammadTheBoss** [comment]
+1

**Comment by trenkwill** [comment]
+ 1

**Comment by skirem** [comment]
+1

**Comment by sgsvenkatesh** [comment]
+1

**Comment by pingshunhuangalex** [comment]
+1

**Comment by sgsvenkatesh** [comment]
+1

**Comment by Eco4** [comment]
+1

**Comment by aki77** [comment]
Please try it!
[emmet](https://atom.io/packages/emmet) package is required.

`~/.atom/config.cson`

```cson
'.text.html':
  'expand-region':
    commands: [
      {
        command: 'editor:select-word'
        recursive: false
      }
      {
        command: 'emmet:balance-outward'
        recursive: true
      }
      {
        command: 'expand-region:select-inside-single-quotes'
        recursive: false
      }
      {
        command: 'expand-region:select-around-single-quotes'
        recursive: false
      }
      {
        command: 'expand-region:select-inside-double-quotes'
        recursive: false
      }
      {
        command: 'expand-region:select-around-double-quotes'
        recursive: false
      }
      {
        command: 'expand-region:select-inside-angle-brackets'
        recursive: false
      }
      {
        command: 'expand-region:select-around-angle-brackets'
        recursive: false
      }
    ]
```
