### ISSUE TITLE
expand must select line before block

### ISSUE THREAD

**Issue by cocodrino** [aki77/atom-expand-region#6]
Hi, first thanks for this extension, I was missing this feature, secondly, I think than would be a big improve if before select block the expansion selects the entire line before, hope you implement this in a future, thank you!.....

**Comment by VoronaPavel** [comment]
+1 would be nice

**Comment by VoronaPavel** [comment]
@cocodrino We can configure expected behavior. See this https://github.com/aki77/atom-expand-region/issues/3
