### ISSUE TITLE
Add documentation for customizing

### ISSUE THREAD

**Issue by stevenhauser** [aki77/atom-expand-region#7]
Hello. This is by far one of my favorite packages, so thanks for putting it together! I did have some issues figuring out how the customization works though, as the `README` doesn't explain it too thoroughly. What do you think about adding a bit more info and perhaps an example, like:

---

## Customize selected regions

Follow [the Atom guide](https://atom.io/docs/latest/using-atom-basic-customization#language-specific-settings-in-your-config-file) on language-specific configuration to adjust how regions are selected per language. Edit `~/.atom/config.cson` and use the [default settings](https://github.com/aki77/atom-expand-region/blob/master/settings/expand-region.cson) as a reference.

For example, if you want to select words with dashes first in CSS (instead of words without dashes), you could change your `config.cson` to something like:

```cson
'.source.css':
  'expand-region':
    commands: [
      # Note how `expand-region:select-word` is no longer here 
      # like it is in the defaults
      {
        command: 'expand-region:select-word-include-dash',
        recursive: false
      }
      # etc...
    ]
```

And now if you expanded while your cursor was—for example—between `x` and `t` in `text-align`, rather than selecting `text` first, you'd select the whole `text-align` property.

**Comment by aki77** [comment]
I welcome the pull request because English is not good. :cry:

**Comment by aki77** [comment]
Thanks! :smiley:
