### ISSUE TITLE
not working windows 8 64 bit

### ISSUE THREAD

**Issue by kh82** [aki77/atom-expand-region#9]
Installed this package, restarted atom. 

Package doesn't appear inside the packages menu, the shortcuts don't work and when I paste the suggested shortcuts into the keymap, it doesn't do anything. 

Does this plugin still work?

**Comment by aki77** [comment]
Please edit `keymap.cson`.

```
'atom-text-editor':
  'alt-up': 'expand-region:expand'
  'alt-down': 'expand-region:shrink'
```

**Comment by bestander** [comment]
Worked for me on windows 10, wow, thanks a lot for this package.
Such a small thing but I think this is my favourite from webstorm :)
